# -*- coding: utf-8 -*-
{
    'name': 'Expense Management',
    'version': '1.0',
    'author': 'Stack Over Flowers',
    'license': "OPL-1",
    'depends': ['base','contacts', 'web', 'hr','hr_expense','mail'],
    'data': ['data/sequence.xml',
             'security/ir.model.access.csv',
             'views/approval_rule_view.xml',
             'views/expense_claim_view.xml',
             'views/res_company.xml',
             'views/employee_views.xml',
             'views/hr_expense_views.xml',
             'views/reset_password_template.xml',
             'views/signup_template.xml',
             ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
